// ─────────────────────────────────────────────────────────────────────────────
// Industry-specific demo dashboard configurations
// ─────────────────────────────────────────────────────────────────────────────

const DEMOS = {

  property: {
    name:             'Mountain Properties',
    subtitle:         'Intelligent Leasing · Zero Missed Calls',
    phone:            '(970) 555-2323',
    agentName:        'Sarah',
    kpi1:             { label: 'Leasing Leads',            sub: 'housing & residential inquiries' },
    kpi2:             { label: 'Maintenance Calls Handled', sub: 'routed without staff involvement' },
    kpi3:             { label: 'Estimated Lead Value',      sub: '@ $250 per leasing lead' },
    kpi4:             { label: 'After-Hours Handled',       sub: 'captured outside 9am–5pm' },
    kpi2Icon:         '🔧',
    afterHoursStart:  9,
    afterHoursEnd:    17,
    kpi1Types:        ['student housing', 'residential rental'],
    kpi2Types:        ['maintenance request', 'emergency'],
    valueCategory:    ['student housing', 'residential rental'],
    valuePerLead:     250,
    badges: {
      'Student Housing':    'badge-housing',
      'Residential Rental': 'badge-residential',
      'Maintenance Request':'badge-maintenance',
      'Emergency':          'badge-emergency',
    },
    leads: [
      { name: 'Sarah Allenberger', phone: '970-555-3847', type: 'Student Housing',    notes: 'Inquiring about 2BR availability for fall semester.',       date: '2026-04-05T20:15:00Z' },
      { name: 'Jake Morales',      phone: '970-555-7291', type: 'Student Housing',    notes: 'Furnished studio for fall, prefers close to campus.',        date: '2026-04-04T02:45:00Z' },
      { name: 'David Kim',         phone: '970-555-8163', type: 'Residential Rental', notes: 'Relocating from Denver, needs 2BR by June 1st.',             date: '2026-04-01T17:45:00Z' },
      { name: 'Laura Simmons',     phone: '970-555-3491', type: 'Residential Rental', notes: 'Young professional, wants 1BR with in-unit laundry.',        date: '2026-04-08T00:00:00Z' },
      { name: 'Tom Bradley',       phone: '970-555-1847', type: 'Maintenance Request',notes: 'Garbage disposal not working in unit 14B.',                  date: '2026-04-04T14:30:00Z' },
      { name: 'Ashley Bennett',    phone: '970-555-9036', type: 'Student Housing',    notes: 'Pet-friendly unit near CSU, move-in August.',                date: '2026-04-10T00:50:00Z' },
      { name: 'Marcus Rivera',     phone: '970-555-4492', type: 'Residential Rental', notes: 'Family of three, looking for 3BR with yard.',                date: '2026-04-10T20:00:00Z' },
      { name: 'Jessica Park',      phone: '970-555-7634', type: 'Maintenance Request',notes: 'HVAC making noise, needs inspection.',                       date: '2026-04-09T23:45:00Z' },
    ],
  },

  hvac: {
    name:             'Peak HVAC Solutions',
    subtitle:         'Service Calls · Emergency Routing · 24/7',
    phone:            '(970) 555-4193',
    agentName:        'Aria',
    kpi1:             { label: 'Service Requests',         sub: 'new jobs captured by AI' },
    kpi2:             { label: 'Emergency Calls Routed',   sub: 'handled without voicemail' },
    kpi3:             { label: 'Estimated Job Value',      sub: '@ $350 per service call' },
    kpi4:             { label: 'After-Hours Handled',      sub: 'captured outside 8am–5pm' },
    kpi2Icon:         '🚨',
    afterHoursStart:  8,
    afterHoursEnd:    17,
    kpi1Types:        ['ac repair', 'heating service', 'maintenance'],
    kpi2Types:        ['emergency'],
    valueCategory:    ['ac repair', 'heating service', 'maintenance'],
    valuePerLead:     350,
    badges: {
      'AC Repair':       'badge-residential',
      'Heating Service': 'badge-housing',
      'Emergency':       'badge-emergency',
      'Maintenance':     'badge-maintenance',
    },
    leads: [
      { name: 'Brian Holloway',  phone: '970-555-2918', type: 'AC Repair',       notes: 'AC not cooling, unit is 8 years old.',                  date: '2026-04-05T21:00:00Z' },
      { name: 'Karen Mills',     phone: '970-555-6374', type: 'Emergency',       notes: 'No heat, temperature dropping — needs same-day service.',date: '2026-04-03T03:15:00Z' },
      { name: 'Derek Santos',    phone: '970-555-8821', type: 'Heating Service', notes: 'Annual furnace tune-up before winter.',                  date: '2026-04-06T10:45:00Z' },
      { name: 'Pam Nguyen',      phone: '970-555-4102', type: 'AC Repair',       notes: 'Strange noise from outdoor unit, wants estimate.',       date: '2026-04-08T19:30:00Z' },
      { name: 'Steve Caldwell',  phone: '970-555-7563', type: 'Maintenance',     notes: 'Filter replacement and duct inspection.',                date: '2026-04-09T09:00:00Z' },
      { name: 'Lisa Tran',       phone: '970-555-3347', type: 'Emergency',       notes: 'AC stopped working with guests visiting this weekend.',  date: '2026-04-11T22:10:00Z' },
      { name: 'Tom Garrett',     phone: '970-555-9184', type: 'Heating Service', notes: 'New construction install, needs quote.',                 date: '2026-04-10T14:00:00Z' },
    ],
  },

  dental: {
    name:             'Frontier Dental Care',
    subtitle:         'New Patient Intake · Appointment Capture · 24/7',
    phone:            '(970) 555-7731',
    agentName:        'Nova',
    kpi1:             { label: 'New Patients Captured',    sub: 'intake handled by AI' },
    kpi2:             { label: 'Appointment Requests',     sub: 'logged for front desk follow-up' },
    kpi3:             { label: 'Estimated Patient Value',  sub: '@ $1,500 per new patient' },
    kpi4:             { label: 'After-Hours Captured',     sub: 'outside 8am–5pm' },
    kpi2Icon:         '📅',
    afterHoursStart:  8,
    afterHoursEnd:    17,
    kpi1Types:        ['new patient'],
    kpi2Types:        ['appointment request'],
    valueCategory:    ['new patient', 'appointment request'],
    valuePerLead:     1500,
    badges: {
      'New Patient':          'badge-housing',
      'Appointment Request':  'badge-residential',
      'Emergency':            'badge-emergency',
      'Insurance Question':   'badge-maintenance',
    },
    leads: [
      { name: 'Mia Henderson',   phone: '970-555-2019', type: 'New Patient',         notes: 'Moving to Fort Collins, needs new dentist for family of 4.',  date: '2026-04-05T20:30:00Z' },
      { name: 'Ryan Kowalski',   phone: '970-555-5538', type: 'Appointment Request', notes: 'Toothache, wants earliest available slot.',                    date: '2026-04-04T07:45:00Z' },
      { name: 'Angela Ford',     phone: '970-555-8847', type: 'New Patient',         notes: 'Looking for a dentist that accepts Delta Dental.',             date: '2026-04-06T18:00:00Z' },
      { name: 'Josh Patel',      phone: '970-555-3362', type: 'Appointment Request', notes: 'Routine cleaning and X-rays.',                                 date: '2026-04-08T12:15:00Z' },
      { name: 'Carla Reyes',     phone: '970-555-6671', type: 'Emergency',           notes: 'Chipped tooth from fall, needs urgent care.',                  date: '2026-04-09T22:40:00Z' },
      { name: 'Sam Whitfield',   phone: '970-555-1129', type: 'New Patient',         notes: 'Interested in whitening and general checkup.',                 date: '2026-04-11T08:00:00Z' },
      { name: 'Nina Okafor',     phone: '970-555-4480', type: 'Insurance Question',  notes: 'Asking about payment plans and insurance coverage.',           date: '2026-04-10T16:30:00Z' },
    ],
  },

  salon: {
    name:             'Luxe Hair Studio',
    subtitle:         'Booking Capture · New Client Intake · 24/7',
    phone:            '(970) 555-2847',
    agentName:        'Belle',
    kpi1:             { label: 'Bookings Captured',        sub: 'appointments logged by AI' },
    kpi2:             { label: 'New Client Inquiries',     sub: 'first-time callers handled' },
    kpi3:             { label: 'Estimated Revenue',        sub: '@ $120 per new client visit' },
    kpi4:             { label: 'After-Hours Bookings',     sub: 'captured outside salon hours' },
    kpi2Icon:         '👤',
    afterHoursStart:  10,
    afterHoursEnd:    19,
    kpi1Types:        ['appointment request', 'color service'],
    kpi2Types:        ['new client'],
    valueCategory:    ['new client', 'appointment request', 'color service'],
    valuePerLead:     120,
    badges: {
      'New Client':           'badge-housing',
      'Appointment Request':  'badge-residential',
      'Color Service':        'badge-maintenance',
      'Product Inquiry':      'badge-residential',
    },
    leads: [
      { name: 'Taylor Brooks',  phone: '970-555-3821', type: 'New Client',          notes: 'Looking for a new stylist, wants balayage consultation.',  date: '2026-04-05T19:45:00Z' },
      { name: 'Jenna Alvarez',  phone: '970-555-7243', type: 'Appointment Request', notes: 'Cut and color, available weekday mornings.',               date: '2026-04-04T08:30:00Z' },
      { name: 'Diana Moore',    phone: '970-555-5590', type: 'Color Service',       notes: 'Highlights touch-up, been a client before.',               date: '2026-04-06T17:00:00Z' },
      { name: 'Erica Nguyen',   phone: '970-555-6318', type: 'New Client',          notes: 'Wants full color and cut, flexible on timing.',            date: '2026-04-08T21:15:00Z' },
      { name: 'Sophie Grant',   phone: '970-555-2204', type: 'Appointment Request', notes: 'Blowout for a wedding this Saturday.',                     date: '2026-04-09T07:50:00Z' },
      { name: 'Alexis Turner',  phone: '970-555-8843', type: 'New Client',          notes: 'Referred by Diana Moore, wants a consultation.',           date: '2026-04-11T20:00:00Z' },
      { name: 'Rachel Kim',     phone: '970-555-4417', type: 'Product Inquiry',     notes: 'Asking about keratin treatment pricing.',                  date: '2026-04-10T15:00:00Z' },
    ],
  },

  auto: {
    name:             'Summit Auto Repair',
    subtitle:         'Job Capture · Appointment Intake · 24/7',
    phone:            '(970) 555-6612',
    agentName:        'Rex',
    kpi1:             { label: 'Jobs Captured',            sub: 'service requests logged by AI' },
    kpi2:             { label: 'Emergency Calls Handled',  sub: 'tow & urgent requests routed' },
    kpi3:             { label: 'Estimated Job Value',      sub: '@ $280 per repair job' },
    kpi4:             { label: 'After-Hours Captured',     sub: 'outside 8am–6pm' },
    kpi2Icon:         '🚨',
    afterHoursStart:  8,
    afterHoursEnd:    18,
    kpi1Types:        ['repair request', 'estimate', 'appointment'],
    kpi2Types:        ['emergency tow'],
    valueCategory:    ['repair request', 'estimate', 'appointment'],
    valuePerLead:     280,
    badges: {
      'Repair Request': 'badge-housing',
      'Estimate':       'badge-residential',
      'Emergency Tow':  'badge-emergency',
      'Appointment':    'badge-maintenance',
    },
    leads: [
      { name: 'Mike Donovan',   phone: '970-555-4421', type: 'Repair Request', notes: 'Check engine light on, runs rough at idle.',              date: '2026-04-05T20:00:00Z' },
      { name: 'Sandra Weiss',   phone: '970-555-3318', type: 'Emergency Tow',  notes: 'Car broke down on I-25, needs tow and diagnosis.',        date: '2026-04-04T01:30:00Z' },
      { name: 'Chris Lawson',   phone: '970-555-8874', type: 'Estimate',       notes: 'Brake job on a 2019 F-150, wants quote.',                 date: '2026-04-06T11:00:00Z' },
      { name: 'Vanessa Cruz',   phone: '970-555-6629', type: 'Appointment',    notes: 'Oil change and tire rotation, weekend appointment.',      date: '2026-04-08T18:45:00Z' },
      { name: 'Doug Perkins',   phone: '970-555-2290', type: 'Repair Request', notes: 'AC blowing warm air, needs recharge or leak check.',      date: '2026-04-10T09:30:00Z' },
      { name: 'Tina Hoffman',   phone: '970-555-7751', type: 'Estimate',       notes: 'Transmission slipping, wants inspection and quote.',      date: '2026-04-11T21:00:00Z' },
      { name: 'Aaron Blake',    phone: '970-555-5583', type: 'Appointment',    notes: 'New customer, full inspection on used car purchase.',     date: '2026-04-12T13:00:00Z' },
    ],
  },

  plumbing: {
    name:             'RapidFlow Plumbing',
    subtitle:         'Emergency Routing · Service Capture · 24/7',
    phone:            '(970) 555-3390',
    agentName:        'Max',
    kpi1:             { label: 'Service Calls Captured',   sub: 'jobs logged by AI' },
    kpi2:             { label: 'Emergency Calls Routed',   sub: 'dispatched without voicemail' },
    kpi3:             { label: 'Estimated Job Value',      sub: '@ $420 per plumbing job' },
    kpi4:             { label: 'After-Hours Handled',      sub: 'captured outside 7am–5pm' },
    kpi2Icon:         '🚨',
    afterHoursStart:  7,
    afterHoursEnd:    17,
    kpi1Types:        ['repair', 'installation', 'inspection'],
    kpi2Types:        ['emergency'],
    valueCategory:    ['repair', 'installation', 'inspection'],
    valuePerLead:     420,
    badges: {
      'Repair':        'badge-residential',
      'Emergency':     'badge-emergency',
      'Installation':  'badge-housing',
      'Inspection':    'badge-maintenance',
    },
    leads: [
      { name: 'Larry Webb',      phone: '970-555-4413', type: 'Emergency',    notes: 'Burst pipe under kitchen sink, water everywhere.',         date: '2026-04-05T02:15:00Z' },
      { name: 'Connie Bass',     phone: '970-555-6628', type: 'Repair',       notes: 'Slow drain in master bath, clog won\'t clear.',            date: '2026-04-04T10:30:00Z' },
      { name: 'Marcus Grant',    phone: '970-555-2291', type: 'Installation', notes: 'New water heater install, 40-gallon unit.',                date: '2026-04-06T14:00:00Z' },
      { name: 'Donna Fletcher',  phone: '970-555-7784', type: 'Emergency',    notes: 'No hot water, family of 5 — urgent.',                     date: '2026-04-08T22:00:00Z' },
      { name: 'Tony Salazar',    phone: '970-555-3356', type: 'Repair',       notes: 'Leaky outdoor hose bib, needs replacement.',              date: '2026-04-09T09:45:00Z' },
      { name: 'Helen Park',      phone: '970-555-8819', type: 'Inspection',   notes: 'Pre-purchase home inspection, full plumbing check.',       date: '2026-04-11T11:00:00Z' },
      { name: 'Greg Cannon',     phone: '970-555-5502', type: 'Installation', notes: 'Bathroom remodel, needs new fixture rough-in.',           date: '2026-04-12T08:30:00Z' },
    ],
  },

};

module.exports = DEMOS;
